artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_download_url: https://github.com/SubinoyBera/
  raw_data_dir: raw_data
  ingestion_dir: ingested_dataset

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: status.txt
  valid_data_dir: valid_data
  books_csvfile: books.csv
  ratings_csvfile: ratings.csv

data_transformation:
  root_dir: artifacts/data_transformation
  valid_books_dataset: valid_books_dataset.csv
  valid_ratings_dataset: valid_ratings_dataset.csv

model_trainer:
  root_dir: artifacts/ML_model
  books_pivot_table: books_pivot_table.pkl
  trained_model: model.pkl